### PR TITLE
Backend support for recording event late/miss

### PR DESCRIPTION
**Pull request by Celeo**
In partial service of #321 if the EC is okay only having the in-built tracking and not the automatic barring of event-signup.

### CODE REVIEW

**Comment by dhawton** [comment]
Why make it so specialized? I'd rather see a generic staff set of action logs similar to the division's than create this while elaborate thing for such a minor task. If we're going to do this really specialized thing, feature flag please so partners can opt out. I feel having a more generalized staff note would be beneficial.

**Comment by Celeo** [comment]
> Why make it so specialized?

Because that's what was asked for. If other members of staff want something generic, then they can ask for it.

**Comment by dhawton** [comment]
> > Why make it so specialized?
> 
> Because that's what was asked for. If other members of staff want something generic, then they can ask for it.

Then it becomes less useful... so feature flag it please. Sometimes making something more general is better even when not asked for if it can be more beneficial to more people. Sometimes users don't know what to ask for.

**Comment by dhawton** [comment]
It might help to have design discussions before doing work that is larger in scale and impacting of more than ZDV so we can discuss items like this before work is done.

**Comment by Celeo** [comment]
> Sometimes users don't know what to ask for

Thankfully, you know better.

If I wanted to spend time guessing what users want, I would become a Project Manager.

**Comment by dhawton** [comment]
> > Sometimes users don't know what to ask for
> 
> Thankfully, you know better.
> 
> If I wanted to spend time guessing what users want, I would become a Project Manager.

Hence why I am in the ZDV discord still, so we can have discussions on implementations. The logic here is flawed. Firstly, you're only implementing counters, and exposing this to non-authed users and non-staff. This kind of data shouldn't be public. Secondly, is the expectation that the EC remember after X days to go and decrement the "offense"? Lastly, if there are 3 tardies or no-shows, are they from the last week, month, year? A more generic action log allows the EC to say "Late for X event" and it would be timestamped via the created_at field, and it could be used for other purposes as well outside of just events.

**Pull request closed without merging**
